joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

left_arm_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - left_arm_shoulder_pan_joint
    - left_arm_shoulder_lift_joint
    - left_arm_elbow_joint
    - left_arm_wrist_1_joint
    - left_arm_wrist_2_joint
    - left_arm_wrist_3_joint
  gains: 
    left_arm_shoulder_pan_joint: {p: 4000,  d: 200, i: 1, i_clamp: 1}
    left_arm_shoulder_lift_joint: {p: 10000,  d: 200, i: 1, i_clamp: 1}
    left_arm_elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
    left_arm_wrist_1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    left_arm_wrist_2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    left_arm_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    left_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 50
  action_monitor_rate: 10

right_arm_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - right_arm_shoulder_pan_joint
    - right_arm_shoulder_lift_joint
    - right_arm_elbow_joint
    - right_arm_wrist_1_joint
    - right_arm_wrist_2_joint
    - right_arm_wrist_3_joint
  gains: 
    right_arm_shoulder_pan_joint: {p: 4000,  d: 200, i: 1, i_clamp: 1}
    right_arm_shoulder_lift_joint: {p: 10000,  d: 200, i: 1, i_clamp: 1}
    right_arm_elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
    right_arm_wrist_1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    right_arm_wrist_2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    right_arm_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    right_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    right_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    right_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
    right_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    right_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    right_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 50
  action_monitor_rate: 10
